# Generated by Django 3.2.3 on 2021-05-15 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=200)),
                ('ProductPrice', models.IntegerField()),
                ('ProductImage', models.ImageField(upload_to='media')),
            ],
        ),
    ]
