# Generated by Django 3.2.3 on 2021-05-15 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartproducts',
            name='ProductImage',
            field=models.ImageField(upload_to='media'),
        ),
    ]
